ID-2739: Aggregate TS annotation status upwards in hierarchy
equinor/ioc-hierarchy-service pull request #28
Opened 2021-06-07 13:33 UTC by erikmaland

2021-06-29 21:19 UTC, pettermk requested changes
As we discussed it might be possible to optimize this to avoid frequently searching the `node_severity_` array. Also small comment regarding formatting

2021-07-05 15:13 UTC, erikmaland commented on tag_hierarchy/unittests/test_severity_field.cpp
> +
Fixed editing of function to the established style.

2021-07-05 15:14 UTC, erikmaland commented
> As we discussed it might be possible to optimize this to avoid frequently searching the `node_severity_` array. Also small comment regarding formatting

I did not manage to use the path-variable as we discussed. The reason being that the severity property is not written to it during the traversal.

Did get rid of one call to `find()` on the map. Also changed from `find()` to `count()` as this call does not construct an iterator.

2021-08-18 10:33 UTC, pettermk approved these changes
Good work!

2021-08-18 10:41 UTC, merged